version: '3'

services:
  agola:
    image: sorintlab/agola
    container_name: agola
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.agola.rule=Host(`agola.localdomain`)"
      - "traefik.http.routers.agola.entrypoints=http"
      - "traefik.http.services.agola.loadbalancer.server.port=8000"
    volumes:
      - "./agoladata:/data/agola"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./config.yml:/config.yml"
    command: serve --embedded-etcd --components all-base,executor
    networks:
      cistack:

  gitea:
    image: gitea/gitea:latest
    container_name: gitea
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.gitea-web.rule=Host(`gitea.localdomain`)"
      - "traefik.http.routers.gitea-web.entrypoints=http"
      - "traefik.http.routers.gitea-web.service=gitea-web-svc"
      - "traefik.http.services.gitea-web-svc.loadbalancer.server.port=3000"
      - "traefik.tcp.routers.gitea-ssh.rule=HostSNI(`*`)"
      - "traefik.tcp.routers.gitea-ssh.entrypoints=ssh"
      - "traefik.tcp.routers.gitea-ssh.service=gitea-ssh-svc"
      - "traefik.tcp.services.gitea-ssh-svc.loadbalancer.server.port=22"
    environment:
      - USER_UID=1000
      - USER_GID=1000
    volumes:
      - "./giteadata:/data"
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    networks:
      cistack:

  traefik:
    image: "traefik:v2.2"
    container_name: "traefik"
    command:
      #- "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.http.address=:80"
      - "--entrypoints.ssh.address=:22"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      cistack:
        aliases:
          - gitea.localdomain
          - agola.localdomain

networks:
  cistack:
